version: '3.7'
services:
    postgres:                                           # create postgres container
        image: postgres:alpine
        container_name: postgres_container
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5436:5436"

    airflow:
        build: './.docker/airflow'
        container_name: airflow_container
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - ./models:/usr/local/airflow/models # Volume em que o modelo gerado é armazenado
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    mlflow:
        build: './.docker/mlflow'
        container_name: mlflow_container
        ports:
            - "5000:5000"
        # Volume compartilhado entre o Airflow (que gera o model)
        # e o MLflow (que faz a leitura)
        # * --default-artifact-root ./models
        volumes:
            - "./models:/models"