version: '3.7'

services:
    fastapi:
        build:
            context: ../
            dockerfile: ./.docker/Dockerfile
        container_name: fast_api_container
        ports:
            - "8081:8081"